### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by web20opensource** [michaelficarra/FunctionalJS#3]
I want to use [Sourcegraph](https://sourcegraph.com) for FunctionalJS code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/michaelficarra/FunctionalJS. (It should only take 30 seconds.)

Thank you!

**Comment by web20opensource** [comment]
thanks!

**Comment by michaelficarra** [comment]
Oh, boy. I am reminded that this project exists. This is an ancient one-man experiment, and it is not a good example of modern best practices. Please use a more modern and maintained library. I hear people are fond of [Ramda](http://ramdajs.com/) nowadays.
